Document: openhrp3
Title: Debian openhrp3 Manual
Author: <insert document author here>
Abstract: This manual describes what openhrp3 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/openhrp3/openhrp3.sgml.gz

Format: postscript
Files: /usr/share/doc/openhrp3/openhrp3.ps.gz

Format: text
Files: /usr/share/doc/openhrp3/openhrp3.text.gz

Format: HTML
Index: /usr/share/doc/openhrp3/html/index.html
Files: /usr/share/doc/openhrp3/html/*.html
