#!/bin/bash
set -e
if [ "$1" = "configure" ]; then
  mkdir -p /usr/share/hrpsys/python
  cd /usr/share/hrpsys/idl
  omniidl -bpython -C/usr/share/hrpsys/python -I/usr/include/openrtm-1.1/rtm/idl *.idl 
  cd /usr/share/hrpsys/python
  python -m compileall .
fi
